builders:
  dto_logger:
    import: "package:dto_logger_generator/dto_logger_generator.dart"
    builder_factories: ["dtoLoggerBuilder"]
    build_extensions: {".dart": [".dto_logger.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
